name: Github-action-demo

on:
  pull_request:
    branches:
      - master
    types:
      - closed
#   push:
#     branches: [ master ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_NEW }}
          password: ${{ secrets.DOCKERHUB_TOKEN_NEW }}
      - name: Build & push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME_NEW }}
        run: |
          export VERSION=$(cat service.yaml)
          export CF_IMAGE=$DOCKERHUB_USERNAME/${{ github.event.repository.name }}:$VERSION
          echo "CF_IMAGE=$CF_IMAGE" >> $GITHUB_ENV
          docker build . --file Dockerfile --build-arg COLOR=$VERSION --tag $CF_IMAGE && docker push $CF_IMAGE
      
     
      - name: report image
        with:
          # Name of runtime to implement the enrichment
          CF_RUNTIME_NAME: 'codefresh-hosted'

          # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

          # Image path to enrich
          CF_IMAGE: ${{env.CF_IMAGE}}

          # Name of Container registry integration
          CF_CONTAINER_REGISTRY_INTEGRATION: 'dockerhub-test'

          # The git branch relevant to the commit
#           CF_GIT_BRANCH: '[name-of-your-git-branch]'

#           # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
#           # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
#           CF_GITHUB_TOKEN: ${{secrets.PAT_NEW}}

          # Git branch with the commit  Pull Request data to add to the image. Pass the branch from the event payload used to trigger your action.
          CF_GIT_BRANCH: ${{ github.event.pull_request.head.ref }}

          # GitHub authentication token. !! Committing a plain text token is a security risk. We highly recommend using encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

          # Issue tracking integration to use to enrich the image.
          CF_JIRA_INTEGRATION: 'jira-test'

          # Jira project prefix  identifying the ticket number to use.
          CF_JIRA_PROJECT_PREFIX: 'CR'

          # Search for issue IDs matching this string to associate with your image.
          CF_JIRA_MESSAGE: ${{ github.event.pull_request.head.ref }}

        uses: codefresh-io/codefresh-report-image@latest
